require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.bufferline"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesiter"
require "user.prettier"
require "user.gitsigns"
require "user.autopairs"
require "user.nvim-tree"
require "user.transparency"

